version: '3.9'
services:
  #MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  #NodeJS API service
  api:
    build: .
    ports:
      # - local machine port:container port
      - 4000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb+srv://root:Admin1..@cluster0.kyjhf.mongodb.net/?retryWrites=true&w=majority
      DB_NAME: products
      NAME: Daniels
    depends_on:
      - mongo_db
volumes:
  mongo_db: {}